[[pages]]
path = "Home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "my_pages/Sampling.py"
name = "Intro to Sampling"
icon = "âˆ­"

[[pages]]
path = "my_pages/Probability_Review.py"
name = "Proability Theory"
icon = "%"